---
title: "DataAppendix"
author: "Zainab"
date: "11/7/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(readr)
library(mosaic)
collegedata <- read_csv("data.csv")
collegeChardata <- read_csv("data2.csv")
```

```{r}
str(collegedata, give.attr = FALSE)
newData = inner_join(collegeChardata, collegedata, by="name")
# x variables: tier, hbcu, grad_rate_150_p_, sticker_price_, black_share_fall, alien_share_fall, pct_stem_2000, par_median, Counts, endowment_pc_
# y variable: kq5_cond_parq1
```


```{r}
favstats(~tier, data=newData)
```

```{r}
favstats(~hbcu, data=newData)
```

```{r}
favstats(~grad_rate_150_p_2013, data=newData)
```

```{r}
favstats(~sticker_price_2013, data=newData)

```

```{r}
favstats(~black_share_fall_2000, data=newData)
```

```{r}
favstats(~alien_share_fall_2000, data=newData)
```


```{r}
favstats(~pct_stem_2000, data=newData)
```

```{r}
favstats(~par_median, data=newData)
```


```{r}
favstats(~count, data=newData)
```

```{r}
favstats(~endowment_pc_2000, data=newData)
```

Y variable: 
```{r}
favstats(~kq5_cond_parq1, data=newData)
```

```{r}

```

