---
title: "Draft Project"
author: ""
date: "11/7/2017"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(readr)
library(mosaic)
library(ggplot2)
require(magrittr)
require(tidyverse)
require(leaps)
require(Stat2Data)
require(leaps)
library(leaps)
collegedata <- read_csv("data.csv")
collegeChardata <- read_csv("data2.csv")
```

```{r}
newData = inner_join(collegeChardata, collegedata, by="name")

str(newData)

```

Stepwise Regression
```{r}
#just to remove missing values of variables 
newData = newData%>%
  filter(!is.na(tier),!is.na(hbcu),!is.na(black_share_fall_2000),!is.na(alien_share_fall_2000),!is.na(pct_stem_2000),
         !is.na(par_median),!is.na(endowment_pc_2000),!is.na(count),!is.na(kq5_cond_parq1))

nullmodel <- lm(kq5_cond_parq1~1, data = newData)
fullmodel <- lm(kq5_cond_parq1~tier + hbcu + black_share_fall_2000 + alien_share_fall_2000 + pct_stem_2000 + par_median + endowment_pc_2000 + count, data = newData)

# With 'scale=fullMSE', the AIC term can be interpreted as Cp
fullMSE <- (summary(fullmodel)$sigma)^2

step(nullmodel, scope = list(upper = fullmodel),
scale = fullMSE, direction = "both")
```

```{r}
summary(lm(kq5_cond_parq1~tier + black_share_fall_2000 + alien_share_fall_2000 + pct_stem_2000 + par_median + endowment_pc_2000, data = newData))
```



```{r}
##allsubsets<-regsubsets(kq5_cond_parq1~ count + endowment_pc_2000+par_median+pct_stem_2000+alien_share_fall_2000+ black_share_fall_2000+ scorecard_netprice_2013+ grad_rate_150_p_2013 +hbcu+ tier, data= newData)
# allsubsets<-regsubsets(kq5_cond_parq1~ count + endowment_pc_2000+par_median+pct_stem_2000+alien_share_fall_2000+ black_share_fall_2000 +hbcu+ tier, data= newData)
# plot(allsubsets, scale= "adjr2")
m1<-plot(kq5_cond_parq1~endowment_pc_2000+par_median+pct_stem_2000+alien_share_fall_2000+ black_share_fall_2000+ tier, data= newData)
Lm1<-lm(kq5_cond_parq1~endowment_pc_2000+par_median+pct_stem_2000+alien_share_fall_2000+ black_share_fall_2000+ tier, data= newData)
summary(Lm1)
m1
```

# Transforming the response

```{r}
c <- ggplot(newData, aes(kq5_cond_parq1))
c+geom_histogram()

newData = newData %>%
  mutate(sqrtkq5_cond_parq1 = sqrt(kq5_cond_parq1))
d <- ggplot(newData, aes(sqrtkq5_cond_parq1))
d+geom_histogram()

newData = newData %>%
  mutate(logendowment_pc_2000 = log(endowment_pc_2000))
e <- ggplot(newData, aes(logendowment_pc_2000))
e+geom_histogram()

newData = newData %>%
  mutate(logpct_stem_2000 = log(pct_stem_2000))
f <- ggplot(newData, aes(logpct_stem_2000))
f+geom_histogram()

newData = newData %>%
  mutate(logalien_share_fall_2000 = sq(alien_share_fall_2000))
g <- ggplot(newData, aes(logalien_share_fall_2000))
g+geom_histogram()


```


```{r}
allsubsets<-regsubsets(sqrtkq5_cond_parq1~ count + logendowment_pc_2000+par_median+pct_stem_2000+alien_share_fall_2000+ black_share_fall_2000 +hbcu+ tier, data=newData)
plot(allsubsets, scale= "adjr2")

```

```{r}
m1<-plot(sqrtkq5_cond_parq1~logendowment_pc_2000+par_median+pct_stem_2000+alien_share_fall_2000+ black_share_fall_2000+ tier, data= newData)
Lm1<-lm(sqrtkq5_cond_parq1~logendowment_pc_2000+par_median+pct_stem_2000+alien_share_fall_2000+ black_share_fall_2000+ tier, data= newData)
summary(Lm1)
m1
```

1. Assumption for regression
2. Assumptions for inference
3. Choosing predictors
4. Testing 
5. Residuals
6. Interpretation 

